[package]
name = "game-runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
engine-assets = { path = "../../crates/engine-assets" }
engine-core = { path = "../../crates/engine-core" }
engine-diagnostics = { path = "../../crates/engine-diagnostics" }
engine-project = { path = "../../crates/engine-project" }
engine-runner = { path = "../../crates/engine-runner" }
log.workspace = true
