[package]
name = "engine-runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
engine-assets = { path = "../engine-assets" }
engine-audio = { path = "../engine-audio" }
engine-core = { path = "../engine-core" }
engine-input = { path = "../engine-input" }
engine-lua = { path = "../engine-lua" }
engine-physics = { path = "../engine-physics" }
engine-project = { path = "../engine-project" }
engine-reflect = { path = "../engine-reflect" }
engine-render = { path = "../engine-render" }
engine-scene = { path = "../engine-scene" }
log.workspace = true
