[package]
name = "engine-editor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
engine-assets = { path = "../engine-assets" }
engine-project = { path = "../engine-project" }
engine-core = { path = "../engine-core" }
engine-diagnostics = { path = "../engine-diagnostics" }
engine-lua = { path = "../engine-lua" }
engine-math = { path = "../engine-math" }
engine-physics = { path = "../engine-physics" }
engine-runtime = { path = "../engine-runtime" }
engine-plugin = { path = "../engine-plugin" }
engine-render = { path = "../engine-render" }
engine-reflect = { path = "../engine-reflect" }
engine-scene = { path = "../engine-scene" }

egui.workspace = true
eframe.workspace = true
egui_dock.workspace = true
rfd.workspace = true
dirs.workspace = true
serde.workspace = true
ron.workspace = true
bytemuck.workspace = true
notify.workspace = true
image.workspace = true
gltf.workspace = true

log.workspace = true
