[package]
name = "engine-project"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
engine-assets = { path = "../engine-assets" }
engine-core = { path = "../engine-core" }
engine-plugin = { path = "../engine-plugin" }
log.workspace = true
ron.workspace = true
serde.workspace = true
