[package]
name = "engine-physics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
bevy_reflect.workspace = true
engine-core = { path = "../engine-core" }
engine-assets = { path = "../engine-assets" }
engine-reflect = { path = "../engine-reflect" }
engine-math = { path = "../engine-math" }
log.workspace = true
rapier2d.workspace = true
rapier3d.workspace = true
